name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🆙 Dependency Updates'
    label: 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'feature'
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'dependencies'
      - 'documentation'
  default: patch

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: 'enhancement'
    branch:
      - '/enhancement\/.+/'
      - '/enhance\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'dependencies'
    branch:
      - '/dependencies\/.+/'
      - '/dep\/.+/'
      - '/deps\/.+/'
template: |
  ## Changes

  $CHANGES
  ***
  For full changes, see the [comparison between $PREVIOUS_TAG and $RESOLVED_VERSION](https://github.com/IncPlusPlus/atlast-okta/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)